services:
  - type: web
    name: albion-assistance-bot
    env: node
    plan: free
    buildCommand: npm install --production
    startCommand: npm run start:auto
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: APPLICATION_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: SKIP_DEPLOY
        value: false
        sync: false
      - key: ALLIANCE_WEBHOOK_SECRET
        sync: false
      - key: CALLER_FEE_RATE
        value: "0.05"
        sync: false
